export const dogs = [
    {
        name: "Rex",
        avatar: "images/dog-rex.jpg",
        age: 25,
        bio: "Art. Literature. Natural wine. Yoga.",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 1,
    },
    {
        name: "Bella",
        avatar: "images/dog-bella.jpg",
        age: 43,
        bio: "Yup, that's my owner. U can meet him if you want",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 2,
    },
    {
        name: "Teddy",
        avatar: "images/dog-teddy.jpg",
        age: 30,
        bio: "How you doin?",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 3,
    },
    {
        name: "Skippy",
        avatar: "images/beach-dog.jpg",
        age: 20,
        bio: "Love running on the beach",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 4,
    },
    {
        name: "Bully",
        avatar: "images/pitbull-dog.jpg",
        age: 35,
        bio: "Some say I'm scary but I'm just a big softy at heart",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 5,
    },
    {
        name: "Einstein",
        avatar: "images/reading-dog.jpg",
        age: 40,
        bio: "Quite, love books, enjoy old movies",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 6,
    },
    {
        name: "Casanova",
        avatar: "images/romantic-dog.jpg",
        age: 20,
        bio: "Romance is my middle name!",
        hasBeenSwiped: false,
        hasBeenLiked: false,
        id: 7,
    }
]
